# Generated by Django 3.0.4 on 2020-04-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200325_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
